CREATE TABLE USERS(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
CPF_CNPJ VARCHAR(255) NOT NULL,
is_active BOOLEAN  DEFAULT TRUE
);

CREATE TABLE PRODUTOS (
                          ID INTEGER PRIMARY KEY AUTO_INCREMENT,
                          NAME VARCHAR(255) NOT NULL,
                          QUANTIDADE INT NOT NULL,
                          PRECO DECIMAL(10, 2) NOT NULL
);
